version: "3.7"

services:

  twaddle-kibana:
    container_name: twaddle-kibana
    image: docker.elastic.co/kibana/kibana:6.2.4
    environment:
      - ELASTICSEARCH_URL=http://twaddle-elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - twaddle-elasticsearch
    networks:
      - twaddle-network

  twaddle-elasticsearch:
    container_name: twaddle-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    networks:
      - twaddle-network

  twaddle-rabbitmq:
    container_name: twaddle-rabbitmq
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - twaddle-network

  twaddle-app:
    container_name: twaddle-app
    image: twaddle/twaddle-app
    environment:
      - TWADDLE_MAGICSTRING=Hello Docker!
      - SPRING_CLOUD_STREAM_BINDERS_LOCAL_RABBIT_ENVIRONMENT_SPRING_RABBITMQ_HOST=twaddle-rabbitmq
      - SPRING_DATASOURCE_HIKARI=twaddle-kibana
      - ELASTICSEARCH_ADDRESS=twaddle-elasticsearch
    ports:
      - 1337:1337
    depends_on:
      - twaddle-elasticsearch
      - twaddle-rabbitmq
    restart: on-failure
    networks:
      - twaddle-network

networks:
  twaddle-network:
    external: false