version: "3.7"

services:

  twaddle-kibana:
    container_name: twaddle-kibana
    image: docker.elastic.co/kibana/kibana:6.2.4
    ports:
      - 5601:5601
    depends_on:
      - twaddle-elasticsearch

  twaddle-elasticsearch:
    container_name: twaddle-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - transport.host=0.0.0.0
      - http.host=0.0.0.0
    ports:
      - 9200:9200
      - 9300:9300
